#!/bin/bash
set -e

# On purge, remove systemd unit & app directory
if [ "$1" = "purge" ]; then
    rm -f /etc/systemd/system/alma-scanner.service
    rm -rf /opt/alma-scanner
    systemctl daemon-reload
fi
